# Gin-G Global Configuration

server:
  name: app
  host: http://localhost
  ip: 127.0.0.1
  port: 8090

logger:
  level: info

loggerwriter:
  filename: app.log
  maxsize: 30
  maxbackups: 3
  maxage: 30
  localtime: true
  compress: true

redis:
  host: 192.168.14.128
  port: 6379
  password: foobared
  database: 0

mysql:
  maxidleconns: 5
  maxopenconns: 76
  name: test
  user: root
  password: root
  ip: 127.0.0.1
  port: 3306
  debug: true
  maxlifetime: 120
  automigrate: false
  interpolateparams: true

version:  2.0.1



